minVersion: 0.34.1
github:
  owner: getsentry
  repo: sentry-kafka-schemas
changelogPolicy: auto
targets:
  - name: github
  - name: pypi
  - name: crates
  - name: sentry-pypi
    internalPypiRepo: getsentry/pypi
