[package]
name = "sentry-kafka-schemas-codegen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
schemafy_lib = "0.6.0"
serde_json = "1.0.95"
